##baseurl = 
title = "BSIDES Fort Wayne"
languageCode = "en-us"
pagerSize = "10" # Number of posts per page
theme = "hugo-theme-hello-friend-ng"

[[params.social]]
  name = "Discord"
  url = "<profile_URL>"

[Author]
  name = "BSIDES Fort Wayne Organizers"
  bio = ""
  avatar = "img/logo.png"

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = -100
#  [[menu.main]]
#    name = 'Schedule'
#    url = '/schedule'
#    weight = -90
#  [[menu.main]]
#    name = 'Tickets'
#    url = 'https://www.eventbrite.com/e/bsidesfortwayne-2024-tickets-789388280597'
#    weight = -85
#[[Menu.main]]
#name = 'CTF'
#url = 'https://ctf.bsidesfortwayne.org'
#weight = -82
  [[Menu.main]]
    name = 'About'
    url = '/about'
    weight = -80

[Params.Portrait]
  path="img/logo.png"

[[Params.social]]
  name = "discord"
  url = "https://discord.gg/tM4eZFFzjg"

[[Params.social]]  
  name = "linkedin"
  url = "https://www.linkedin.com/company/bsidesfortwayne"

[[Params.social]]  
  name = "email"
  url = "emailto:bsidesfortwayne@gmail.com"

[[Params.social]]  
  name = "X"
  url = "https://x.com/BSidesFortWayne"

[[Params.social]]
  name="github"
  url="https://github.com/BSidesFortWayne"
   

[Permalinks]
  posts = "posts/:year/:month/:contentbasename"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
