##baseurl = 
title = "BSIDES Fort Wayne"
languageCode = "en-us"
pagerSize = "10" # Number of posts per page
theme = "hugo-theme-hello-friend-ng"

customJS = ['js/encrypt.js']

[Params.logo]
  logoMark     = " "
  logoText     = "BSFW>"
  logoHomeLink = "/"
  logoCursorColor="#268FBF"

[Author]
  name = "BSIDES Fort Wayne Organizers"
  bio = ""
  avatar = "img/logo.png"

[Menu]
  #[[Menus.main]]
  #  identifier = 'Home'
  #  name = 'Home'
  #  url = '/'
  [[Menus.main]]
    identifier = '100'
    name = 'About'
    url = '/about'
  [[Menus.main]]
    identifier = '90'
    name = 'Legal'
    url = '/legal'
  [[Menus.main]]
    identifier = '40'
    name = 'Sponsorships'
    url = 'https://bsidesfortwayne.org/sponsorship'
    params.external = true
  [[Menus.main]]
    identifier = '30'
    name = 'CFP'
    url = 'https://bsidesfortwayne.org/CFP'
    params.external = true
  [[Menus.main]]
    identifier = '20'
    name = 'Tickets'
    url = 'https://bsidesfortwayne.org/tickets'
    params.external = true
  [[Menus.main]]
    identifier = '25'
    name = 'CTF'
    url = 'https://ctf.bsfw.org'
    params.external = true
    
#  [[menu.main]]
#    name = 'Schedule'
#    url = '/schedule'
#    weight = -90
#  [[menu.main]]
#    name = 'Tickets'
#    url = 'https://www.eventbrite.com/e/bsidesfortwayne-2024-tickets-789388280597'
#    weight = -85
#[[Menu.main]]
#name = 'CTF'
#url = 'https://ctf.bsidesfortwayne.org'
#weight = -82


[Params.Portrait]
  path="img/logo.png"

[[Params.social]]
  name = "discord"
  url = "https://discord.gg/tM4eZFFzjg"

[[Params.social]]  
  name = "linkedin"
  url = "https://www.linkedin.com/company/bsidesfortwayne"

[[Params.social]]  
  name = "email"
  url = "mailto:bsidesfortwayne@gmail.com"

[[Params.social]]  
  name = "X"
  url = "https://x.com/BSidesFortWayne"

[[Params.social]]
  name="github"
  url="https://github.com/BSidesFortWayne"
   
# Sponsor Stuff
#
# Tiers
# Platinum = 1
# Gold = 2
# Silver = 3
# Bronze = 4
# Sponsor Stuff
#
# Tiers
# Platinum = 1
# Gold = 2
# Silver = 3
# Bronze = 4
[[Params.sponsors]]
  name="PFW"
  url="https://www.pfw.edu/"
  logo="https://www.pfw.edu/application/themes/pfw-web-templates-1.5/assets/img/purdue-fw-logo.png"
  tier="Platinum"

[[Params.sponsors]]
  name="guidepoint"
  url="https://www.guidepointsecurity.com/"
  logo="https://www.guidepointsecurity.com/wp-content/uploads/2024/03/GPS_Horizontal_White_Text_Reg_Mark_RGB.svg"
  tier="Silver"

[[Params.sponsors]]
  name="armis"
  url="https://www.armis.com/"
  logo="https://www.armis.com/wp-content/themes/armis/resources/images/svg/logo-dark.svg"
  tier="Silver"

  
[Permalinks]
  posts = "posts/:year/:month/:contentbasename"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
